lang: ja
title: 記号論理と情報科学 研究集会
description: SLACS (Symbolic Logic and Computer Science) Website
remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme
github:
  is_project_page: true
  owner_url: https://github.com/slacs-web/slacs-web.github.io
  owner_name: slacs-web
